files: [
  {
    "source": "/translations/en-US.json",
    "dest" : "/translations/en-US.json",
    "translation": "/%locale%.json",
    "update_option": "update_as_unapproved"
  }
]
"pull_request_title": "Crowdin translations for Frontend"
"pull_request_labels": [
  "Pikachu"
]
"commit_message": "fix(): New translations %original_file_name% from Crowdin"
"append_commit_message": false
"pull_request_assignees": ["eswar-kumar-bade"]
